version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - REDIS_URI=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  client:
    build: ./client
    ports:
      - "3005:80"
    depends_on:
      - server
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
